[dependencies]
  # mysql驱动
  mysqlclient4cj = {git = "https://gitcode.com/weixin_64400442/mysqlclient4cj.git", branch="master"}

[package]
  cjc-version = "0.56.4"
  compile-option = "--link-options \"-rpath=.\""
  description = "nothing here"
  link-option = ""
  name = "cjfinal"
  output-type = "executable"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "0.2.5"
  [package.package-configuration]
